// Code generated by "stringer -type=Button"; DO NOT EDIT.

package tomato

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MouseLeft-0]
	_ = x[MouseRight-1]
	_ = x[MouseMiddle-2]
}

const _Button_name = "MouseLeftMouseRightMouseMiddle"

var _Button_index = [...]uint8{0, 9, 19, 30}

func (i Button) String() string {
	if i >= Button(len(_Button_index)-1) {
		return "Button(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
