// Code generated by "stringer -type=EvKind"; DO NOT EDIT.

package tomato

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WinClose-1]
	_ = x[MouMove-2]
	_ = x[MouDown-3]
	_ = x[MouUp-4]
	_ = x[MouScroll-5]
	_ = x[KeyDown-6]
	_ = x[KeyUp-7]
	_ = x[KeyRepeat-8]
	_ = x[RuneTyped-9]
}

const _EvKind_name = "WinCloseMouMoveMouDownMouUpMouScrollKeyDownKeyUpKeyRepeatRuneTyped"

var _EvKind_index = [...]uint8{0, 8, 15, 22, 27, 36, 43, 48, 57, 66}

func (i EvKind) String() string {
	i -= 1
	if i >= EvKind(len(_EvKind_index)-1) {
		return "EvKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EvKind_name[_EvKind_index[i]:_EvKind_index[i+1]]
}
